version: 2.1

# todo: use the full test dir
env:
  test-requires: "[test,extra]"
  test-dir: test
  pytest-args: >-
    -rap
    --durations=20
    --verbose

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python -m pip install --upgrade pip
            pip install --upgrade wheel setuptools
            pip install ".${{ env.test-requires }}"
      - run:
          name: Run tests and collect coverage
          command: pytest ${{ env.pytest-args }} ${{ env.test-dir }} --cov=openbox.acq_optimizer --cov=openbox.acquisition_function --cov=openbox.core --cov=openbox.optimizer --cov=openbox.surrogate --cov=openbox.utils --cov=openbox.visualization --cov-report=xml
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test